// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/rpc/kv.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	K             string                 `protobuf:"bytes,1,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_internal_rpc_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_internal_rpc_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetK() string {
	if x != nil {
		return x.K
	}
	return ""
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	V             []byte                 `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_internal_rpc_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_internal_rpc_kv_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *Value) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	K             string                 `protobuf:"bytes,1,opt,name=k,proto3" json:"k,omitempty"`
	V             string                 `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_internal_rpc_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetK() string {
	if x != nil {
		return x.K
	}
	return ""
}

func (x *PutRequest) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_internal_rpc_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PutResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

var File_internal_rpc_kv_proto protoreflect.FileDescriptor

const file_internal_rpc_kv_proto_rawDesc = "" +
	"\n" +
	"\x15internal/rpc/kv.proto\x12\x04raft\"\x13\n" +
	"\x03Key\x12\f\n" +
	"\x01k\x18\x01 \x01(\tR\x01k\"+\n" +
	"\x05Value\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\f\n" +
	"\x01v\x18\x02 \x01(\fR\x01v\"(\n" +
	"\n" +
	"PutRequest\x12\f\n" +
	"\x01k\x18\x01 \x01(\tR\x01k\x12\f\n" +
	"\x01v\x18\x02 \x01(\tR\x01v\">\n" +
	"\vPutResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\tR\n" +
	"leaderHint2O\n" +
	"\x02KV\x12\x1d\n" +
	"\x03Get\x12\t.raft.Key\x1a\v.raft.Value\x12*\n" +
	"\x03Put\x12\x10.raft.PutRequest\x1a\x11.raft.PutResponseB6Z4github.com/moggan1337/raft-kv-store/internal/rpc;rpcb\x06proto3"

var (
	file_internal_rpc_kv_proto_rawDescOnce sync.Once
	file_internal_rpc_kv_proto_rawDescData []byte
)

func file_internal_rpc_kv_proto_rawDescGZIP() []byte {
	file_internal_rpc_kv_proto_rawDescOnce.Do(func() {
		file_internal_rpc_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_kv_proto_rawDesc), len(file_internal_rpc_kv_proto_rawDesc)))
	})
	return file_internal_rpc_kv_proto_rawDescData
}

var file_internal_rpc_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_rpc_kv_proto_goTypes = []any{
	(*Key)(nil),         // 0: raft.Key
	(*Value)(nil),       // 1: raft.Value
	(*PutRequest)(nil),  // 2: raft.PutRequest
	(*PutResponse)(nil), // 3: raft.PutResponse
}
var file_internal_rpc_kv_proto_depIdxs = []int32{
	0, // 0: raft.KV.Get:input_type -> raft.Key
	2, // 1: raft.KV.Put:input_type -> raft.PutRequest
	1, // 2: raft.KV.Get:output_type -> raft.Value
	3, // 3: raft.KV.Put:output_type -> raft.PutResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_rpc_kv_proto_init() }
func file_internal_rpc_kv_proto_init() {
	if File_internal_rpc_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_kv_proto_rawDesc), len(file_internal_rpc_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_kv_proto_goTypes,
		DependencyIndexes: file_internal_rpc_kv_proto_depIdxs,
		MessageInfos:      file_internal_rpc_kv_proto_msgTypes,
	}.Build()
	File_internal_rpc_kv_proto = out.File
	file_internal_rpc_kv_proto_goTypes = nil
	file_internal_rpc_kv_proto_depIdxs = nil
}
